const abs = (num) => Math.abs(num);
const clamped = (num) => clamp(num, -1.0, 1.0);
const cube = (num) => num**3;
const exp = (num) => E**num;
const gauss = (num) => E**(-0.5 * (num)**2);
const hat = (num) => (1 - min(Math.abs(num), 1));
const identity = (num) => num;
const inv = (num) => 1 / (num + SMALL);
const log = (num) => Math.log(clamp(num, SMALL, num));
const relu = (num) => clamp(num, 0, num);
const elu = (num) => num > 0 ? num : exp(num) - 1;
const sigmoid = (num) => 1 / (1 + exp(-num));
const tanh = (num) => Math.tanh(num);
const square = (num) => num**2;